### ISSUE TITLE
Link error when `fastembed` feature enabled on Windows

### ISSUE THREAD

**Issue by ozaner** [bosun-ai/swiftide#201]
**Describe the bug**
When compiling on Windows with the `fastembed` feature flag enabled, a linker error occurs and compilation cannot proceed.

**To Reproduce**
Simply create a new binary crate with the following code:

`cargo.toml`:
```toml
[package]
name = "test-swiftide"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.1", features = ["full"] }
swiftide = { version = "0.6.7", features = ["fastembed"] }
```

`main.rs`:
```rs
use swiftide::{
    indexing::{IndexingStream, Node, Pipeline},
    integrations::fastembed::FastEmbed,
    transformers::Embed,
};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let nodes = vec!["Test sentence.", "Test sentence 2."];
    let pipeline = Pipeline::from_stream(IndexingStream::iter(
        nodes.into_iter().map(|str| Ok(Node::new(str))),
    ))
    .then_in_batch(10, Embed::new(FastEmbed::try_default()?));

    pipeline.run().await.expect_err("no storage");
    Ok(())
}
```

You don't even need to use `FastEmbed` in the program, as merely enabling the flag will cause the compilation to fail.

**Expected behavior**
The program should compile without error.

**Additional context**
I have installed the MSVC tooling via the Visual Studio installer already.
![image](https://github.com/user-attachments/assets/1a2fb998-2c8e-48d8-82c1-947f0d8117c7)

The error output is long and repetitive, so I've attached it here as a text file: [output.txt](https://github.com/user-attachments/files/16364681/output.txt).
